# Generated by Django 5.2.6 on 2025-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='answer_time_sec',
            field=models.IntegerField(default=10),
        ),
    ]
